### ISSUE TITLE
[BUG] QuickEditor: Null pointer exception when OAuth permission is denied

### ISSUE THREAD

**Issue by hamorillo** [Automattic/Gravatar-SDK-Android#426]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
            	at java.net.URLDecoder.decode(URLDecoder.java:177)
            	at java.net.URLDecoder.decode(URLDecoder.java:143)
            	at com.gravatar.quickeditor.ui.oauth.OAuthPageKt$OAuthPage$2.invoke$lambda$2(OAuthPage.kt:80)
            	at com.gravatar.quickeditor.ui.oauth.OAuthPageKt$OAuthPage$2.$r8$lambda$4ff0PyzsslnBNCJbt0hsDIauFsQ(Unknown Source:0)
            	at com.gravatar.quickeditor.ui.oauth.OAuthPageKt$OAuthPage$2$$ExternalSyntheticLambda0.accept(D8$$SyntheticClass:0)
            	at androidx.activity.ComponentActivity.onNewIntent(ComponentActivity.kt:899)
            	at android.app.Activity.performNewIntent(Activity.java:8613)
            	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1556)
            	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1569)
            	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3962)
            	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3969)
            	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
            	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
            	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
            	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
            	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
            	at android.os.Handler.dispatchMessage(Handler.java:106)
            	at android.os.Looper.loopOnce(Looper.java:205)
            	at android.os.Looper.loop(Looper.java:294)
            	at android.app.ActivityThread.main(ActivityThread.java:8177)
            	at java.lang.reflect.Method.invoke(Native Method)
            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

```

**Comment by AdamGrzybkowski** [comment]
Merged into trunk here https://github.com/Automattic/Gravatar-SDK-Android/pull/435
